{{- if not .Values.telegram.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "telegram.secretName" . }}
  namespace: {{ include "tenant.namespace" . }}
  labels:
    tenant: {{ .Values.tenant.name }}
type: Opaque
stringData:
  bot-token: {{ .Values.telegram.botToken | quote }}
  chat-id: {{ .Values.telegram.chatId | quote }}
{{- end }}